import type { Angel72 } from './types';
import { getZodiacSignFromLongitude, normalizeLongitude } from './constants';

const ANGEL_DATA: readonly Omit<Angel72, 'sign' | 'degreesStart' | 'degreesEnd'>[] = [
  {
    number: 1,
    name: 'Vehuiah',
    hebrew: 'והויה',
    hebrewRoot: 'והו',
    psalm: 'Salmo 3:3',
    psalmText: 'Mas tu, Senhor, és um escudo para mim, a minha glória e o que exalta a minha cabeça.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Vontade, coragem e espírito de liderança.',
  },
  {
    number: 2,
    name: 'Jeliel',
    hebrew: 'יליאל',
    hebrewRoot: 'ילי',
    psalm: 'Salmo 21:20',
    psalmText: 'Mas tu, Senhor, não te alongues de mim; força minha, apressa-te em socorrer-me.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Paz, fidelidade e justiça.',
  },
  {
    number: 3,
    name: 'Sitael',
    hebrew: 'סיטאל',
    hebrewRoot: 'סיט',
    psalm: 'Salmo 90:2',
    psalmText: 'Direi do Senhor: Ele é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Responsabilidade e realização material.',
  },
  {
    number: 4,
    name: 'Elemiah',
    hebrew: 'עלמיה',
    hebrewRoot: 'עלם',
    psalm: 'Salmo 6:4',
    psalmText: 'Volta-te, Senhor, livra a minha alma; salva-me por tua benignidade.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Descoberta de novos caminhos e superação de crises.',
  },
  {
    number: 5,
    name: 'Mahasiah',
    hebrew: 'מהשיה',
    hebrewRoot: 'מהש',
    psalm: 'Salmo 33:4',
    psalmText: 'Porque a palavra do Senhor é reta, e todas as suas obras são fiéis.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Harmonia e purificação espiritual.',
  },
  {
    number: 6,
    name: 'Lelahel',
    hebrew: 'ללהאל',
    hebrewRoot: 'ללה',
    psalm: 'Salmo 9:11',
    psalmText: 'Cantai louvores ao Senhor, que habita em Sião; anunciai entre os povos os seus feitos.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Saúde, iluminação e renome.',
  },
  {
    number: 7,
    name: 'Achaiah',
    hebrew: 'אכאיה',
    hebrewRoot: 'אכא',
    psalm: 'Salmo 102:8',
    psalmText: 'O Senhor é misericordioso e piedoso; tardio em irar-se e grande em benignidade.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Paciência e compreensão dos mistérios da natureza.',
  },
  {
    number: 8,
    name: 'Cahetel',
    hebrew: 'כהתאל',
    hebrewRoot: 'כהת',
    psalm: 'Salmo 94:6',
    psalmText: 'Vinde, adoremos e prostremo-nos; ajoelhemos diante do Senhor que nos criou.',
    divineName: 'El',
    hierarchy: 'Serafins',
    virtues: 'Bênçãos divinas e afastamento de energias negativas.',
  },
  {
    number: 9,
    name: 'Haziel',
    hebrew: 'הזיאל',
    hebrewRoot: 'הזי',
    psalm: 'Salmo 24:6',
    psalmText: 'Lembra-te, Senhor, das tuas misericórdias e das tuas benignidades, porque são eternas.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Perdão, reconciliação e bondade.',
  },
  {
    number: 10,
    name: 'Aladiah',
    hebrew: 'אלדיה',
    hebrewRoot: 'אלד',
    psalm: 'Salmo 32:22',
    psalmText: 'Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Cura e regeneração física e moral.',
  },
  {
    number: 11,
    name: 'Lauviah',
    hebrew: 'לאויה',
    hebrewRoot: 'לאו',
    psalm: 'Salmo 17:47',
    psalmText: 'O Senhor vive; e bendito seja o meu rochedo, e exaltado seja o Deus da minha salvação.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Vitória e proteção contra inveja.',
  },
  {
    number: 12,
    name: 'Hahaiah',
    hebrew: 'ההעיה',
    hebrewRoot: 'ההע',
    psalm: 'Salmo 9:22',
    psalmText: 'Por que te deténs longe, Senhor? Por que te escondes nos tempos de angústia?',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Revelação de mistérios e paz de espírito.',
  },
  {
    number: 13,
    name: 'Iezalel',
    hebrew: 'יזלאל',
    hebrewRoot: 'יזל',
    psalm: 'Salmo 97:6',
    psalmText: 'Os céus anunciam a sua justiça, e todos os povos veem a sua glória.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'União, amizade e fidelidade.',
  },
  {
    number: 14,
    name: 'Mebahel',
    hebrew: 'מבהאל',
    hebrewRoot: 'מבה',
    psalm: 'Salmo 9:10',
    psalmText: 'O Senhor será também um alto refúgio para o oprimido; um alto refúgio em tempos de angústia.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Justiça, verdade e liberdade.',
  },
  {
    number: 15,
    name: 'Hariel',
    hebrew: 'הריאל',
    hebrewRoot: 'הרי',
    psalm: 'Salmo 93:22',
    psalmText: 'Mas o Senhor é o meu alto refúgio; e o meu Deus é a rocha do meu refúgio.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Fé e clareza espiritual.',
  },
  {
    number: 16,
    name: 'Hakamiah',
    hebrew: 'הקמיה',
    hebrewRoot: 'הקם',
    psalm: 'Salmo 87:2',
    psalmText: 'Senhor Deus da minha salvação, diante de ti tenho clamado de dia e de noite.',
    divineName: 'El',
    hierarchy: 'Querubins',
    virtues: 'Honra e libertação de opressores.',
  },
  {
    number: 17,
    name: 'Lauviah',
    hebrew: 'לאויה',
    hebrewRoot: 'לאו',
    psalm: 'Salmo 8:1',
    psalmText: 'Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra!',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Sono reparador e inspiração artística.',
  },
  {
    number: 18,
    name: 'Caliel',
    hebrew: 'כליאל',
    hebrewRoot: 'כלי',
    psalm: 'Salmo 7:9',
    psalmText: 'Julga-me, Senhor, conforme a minha justiça e conforme a integridade que há em mim.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Auxílio jurídico e reconhecimento da verdade.',
  },
  {
    number: 19,
    name: 'Leuviah',
    hebrew: 'לוויה',
    hebrewRoot: 'לוו',
    psalm: 'Salmo 39:2',
    psalmText: 'Esperei com paciência no Senhor, e ele se inclinou para mim, e ouviu o meu clamor.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Memória e inteligência.',
  },
  {
    number: 20,
    name: 'Pahaliah',
    hebrew: 'פהליה',
    hebrewRoot: 'פהל',
    psalm: 'Salmo 119:108',
    psalmText: 'Aceita, Senhor, eu te rogo, as oferendas voluntárias da minha boca; e ensina-me os teus juízos.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Redenção e compreensão das leis divinas.',
  },
  {
    number: 21,
    name: 'Nelchael',
    hebrew: 'נלכאל',
    hebrewRoot: 'נלך',
    psalm: 'Salmo 30:15',
    psalmText: 'Em ti, Senhor, confio; dize à minha alma: Eu sou a tua salvação.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Aprendizado e proteção contra calúnias.',
  },
  {
    number: 22,
    name: 'Ieiaiel',
    hebrew: 'יייאל',
    hebrewRoot: 'ייי',
    psalm: 'Salmo 120:5',
    psalmText: 'O Senhor é quem te guarda; o Senhor é a tua sombra à tua direita.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Sucesso em viagens e comércio.',
  },
  {
    number: 23,
    name: 'Melahel',
    hebrew: 'מלהאל',
    hebrewRoot: 'מלה',
    psalm: 'Salmo 120:8',
    psalmText: 'O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Cura através de plantas e proteção ambiental.',
  },
  {
    number: 24,
    name: 'Hahuiah',
    hebrew: 'חהויה',
    hebrewRoot: 'חהו',
    psalm: 'Salmo 32:18',
    psalmText: 'Eis que os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia.',
    divineName: 'Yah',
    hierarchy: 'Tronos',
    virtues: 'Proteção contra animais e perigos noturnos.',
  },
  {
    number: 25,
    name: 'Nith-Haiah',
    hebrew: 'נתהיה',
    hebrewRoot: 'נתה',
    psalm: 'Salmo 9:2',
    psalmText: 'Louvar-te-ei, Senhor, com todo o meu coração; contarei todas as tuas maravilhas.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Sabedoria, magia branca e sonhos proféticos.',
  },
  {
    number: 26,
    name: 'Haaiah',
    hebrew: 'האאיה',
    hebrewRoot: 'האא',
    psalm: 'Salmo 118:145',
    psalmText: 'Clamei com todo o meu coração; ouve-me, Senhor, e guardarei os teus estatutos.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Justiça e diplomacia.',
  },
  {
    number: 27,
    name: 'Ierathel',
    hebrew: 'ירתאל',
    hebrewRoot: 'ירת',
    psalm: 'Salmo 139:2',
    psalmText: 'Livra-me, Senhor, do homem mau; guarda-me do homem violento.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Confusão de inimigos e propagação da luz.',
  },
  {
    number: 28,
    name: 'Seehiah',
    hebrew: 'שאהיה',
    hebrewRoot: 'שאה',
    psalm: 'Salmo 70:13',
    psalmText: 'Ó Deus, não te alongues de mim; meu Deus, apressa-te em socorrer-me.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Longevidade e proteção contra acidentes.',
  },
  {
    number: 29,
    name: 'Reiiel',
    hebrew: 'רייאל',
    hebrewRoot: 'ריי',
    psalm: 'Salmo 53:6',
    psalmText: 'Eis que Deus é o meu ajudador, o Senhor está com os que sustêm a minha alma.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Zelo pela religiosidade e verdade.',
  },
  {
    number: 30,
    name: 'Omael',
    hebrew: 'אומאל',
    hebrewRoot: 'אום',
    psalm: 'Salmo 70:6',
    psalmText: 'Pois tu és a minha esperança, Senhor Deus; tu és a minha confiança desde a minha mocidade.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Paciência e proteção aos animais.',
  },
  {
    number: 31,
    name: 'Lecahel',
    hebrew: 'לכבאל',
    hebrewRoot: 'לכב',
    psalm: 'Salmo 70:16',
    psalmText: 'Sairei na força do Senhor Deus, farei menção da tua justiça, e só dela.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Iluminação intelectual e sucesso na agricultura.',
  },
  {
    number: 32,
    name: 'Vasariah',
    hebrew: 'ושרהיה',
    hebrewRoot: 'ושר',
    psalm: 'Salmo 32:4',
    psalmText: 'Porque a palavra do Senhor é reta, e todas as suas obras são fiéis.',
    divineName: 'El',
    hierarchy: 'Dominações',
    virtues: 'Justiça e memória.',
  },
  {
    number: 33,
    name: 'Ieuiah',
    hebrew: 'יחויה',
    hebrewRoot: 'יחו',
    psalm: 'Salmo 93:11',
    psalmText: 'O Senhor conhece os pensamentos do homem, que são vaidade.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Submissão e fidelidade dos subordinados.',
  },
  {
    number: 34,
    name: 'Lehahaiah',
    hebrew: 'להחיה',
    hebrewRoot: 'להח',
    psalm: 'Salmo 131:3',
    psalmText: 'Espere Israel no Senhor, desde agora e para sempre.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Obediência e apaziguamento da ira.',
  },
  {
    number: 35,
    name: 'Chavakiah',
    hebrew: 'כוקיה',
    hebrewRoot: 'כוק',
    psalm: 'Salmo 114:1',
    psalmText: 'Amo ao Senhor, porque ele ouviu a minha voz e a minha súplica.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Reconciliação familiar e harmonia doméstica.',
  },
  {
    number: 36,
    name: 'Menadel',
    hebrew: 'מנדאל',
    hebrewRoot: 'מנד',
    psalm: 'Salmo 25:8',
    psalmText: 'Senhor, eu amo a habitação da tua casa e o lugar onde permanece a tua glória.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Manutenção do emprego e libertação de vícios.',
  },
  {
    number: 37,
    name: 'Aniel',
    hebrew: 'אניאל',
    hebrewRoot: 'אני',
    psalm: 'Salmo 79:9',
    psalmText: 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Vitória e quebra de cercos.',
  },
  {
    number: 38,
    name: 'Haamiah',
    hebrew: 'חעמיה',
    hebrewRoot: 'חעם',
    psalm: 'Salmo 90:9',
    psalmText: 'Porque tu, ó Senhor, és o meu refúgio. No Altíssimo fizeste a tua habitação.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Verdade e proteção contra cultos falsos.',
  },
  {
    number: 39,
    name: 'Rehael',
    hebrew: 'רעהאל',
    hebrewRoot: 'רעה',
    psalm: 'Salmo 29:13',
    psalmText: 'Ouve, Senhor, e tem piedade de mim, Senhor, sê o meu ajudador.',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Amor filial e cura de doenças.',
  },
  {
    number: 40,
    name: 'Ieiazel',
    hebrew: 'ייזאל',
    hebrewRoot: 'ייז',
    psalm: 'Salmo 87:15',
    psalmText: 'Por que, Senhor, rejeitas a minha alma? Por que escondes de mim a tua face?',
    divineName: 'Yah',
    hierarchy: 'Potestades',
    virtues: 'Consolo e inspiração para escritores e artistas.',
  },
  {
    number: 41,
    name: 'Hahahel',
    hebrew: 'הההאל',
    hebrewRoot: 'ההה',
    psalm: 'Salmo 119:2',
    psalmText: 'Senhor, livra a minha alma dos lábios mentirosos e da língua enganadora.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Sacerdócio e dedicação espiritual.',
  },
  {
    number: 42,
    name: 'Mikael',
    hebrew: 'מיכאל',
    hebrewRoot: 'מיכ',
    psalm: 'Salmo 120:7',
    psalmText: 'O Senhor te guardará de todo o mal; ele guardará a tua alma.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Ordem política e proteção em viagens.',
  },
  {
    number: 43,
    name: 'Veualiah',
    hebrew: 'ווליה',
    hebrewRoot: 'וול',
    psalm: 'Salmo 87:14',
    psalmText: 'Eu, porém, Senhor, tenho clamado a ti, e de madrugada te esperará a minha oração.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Prosperidade e sucesso em empreendimentos.',
  },
  {
    number: 44,
    name: 'Ielahiah',
    hebrew: 'ילהיה',
    hebrewRoot: 'ילה',
    psalm: 'Salmo 118:108',
    psalmText: 'Aceita, Senhor, eu te rogo, as oferendas voluntárias da minha boca; e ensina-me os teus juízos.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Proteção em batalhas e coragem.',
  },
  {
    number: 45,
    name: 'Sealiah',
    hebrew: 'סאליאל',
    hebrewRoot: 'סאל',
    psalm: 'Salmo 93:18',
    psalmText: 'Quando eu disse: O meu pé vacila; a tua benignidade, Senhor, me susteve.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Recuperação de energias e sucesso em tudo.',
  },
  {
    number: 46,
    name: 'Ariel',
    hebrew: 'עריאל',
    hebrewRoot: 'ערי',
    psalm: 'Salmo 144:9',
    psalmText: 'O Senhor é bom para todos, e as suas misericórdias estão sobre todas as suas obras.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Descoberta de tesouros ocultos e gratidão.',
  },
  {
    number: 47,
    name: 'Asaliah',
    hebrew: 'עשליה',
    hebrewRoot: 'עשל',
    psalm: 'Salmo 104:24',
    psalmText: 'Ó Senhor, quão variadas são as tuas obras! Todas as fizeste com sabedoria.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Elevação espiritual e justiça.',
  },
  {
    number: 48,
    name: 'Mihael',
    hebrew: 'מיהאל',
    hebrewRoot: 'מיה',
    psalm: 'Salmo 97:2',
    psalmText: 'O Senhor manifestou a sua salvação; revelou a sua justiça perante os olhos das nações.',
    divineName: 'El',
    hierarchy: 'Virtudes',
    virtues: 'Fecundidade e harmonia conjugal.',
  },
  {
    number: 49,
    name: 'Vehuel',
    hebrew: 'והואל',
    hebrewRoot: 'והו',
    psalm: 'Salmo 144:3',
    psalmText: 'Grande é o Senhor, e muito digno de louvor, e a sua grandeza inescrutável.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Elevação da alma e humildade.',
  },
  {
    number: 50,
    name: 'Daniel',
    hebrew: 'דניאל',
    hebrewRoot: 'דני',
    psalm: 'Salmo 102:8',
    psalmText: 'Misericordioso e piedoso é o Senhor; longânimo e grande em benignidade.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Eloquência e conforto divino.',
  },
  {
    number: 51,
    name: 'Hahasiah',
    hebrew: 'החשיה',
    hebrewRoot: 'החש',
    psalm: 'Salmo 103:31',
    psalmText: 'A glória do Senhor durará para sempre; o Senhor se alegrará nas suas obras.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Ciência, medicina e sabedoria esotérica.',
  },
  {
    number: 52,
    name: 'Imamiah',
    hebrew: 'עממיה',
    hebrewRoot: 'עממ',
    psalm: 'Salmo 7:18',
    psalmText: 'Eu louvarei ao Senhor segundo a sua justiça, e cantarei louvores ao nome do Senhor Altíssimo.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Destruição do poder de inimigos e libertação.',
  },
  {
    number: 53,
    name: 'Nanael',
    hebrew: 'ננאאל',
    hebrewRoot: 'ננא',
    psalm: 'Salmo 118:75',
    psalmText: 'Bem sei eu, ó Senhor, que os teus juízos são justos, e que com fidelidade me afligiste.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Conhecimento místico e recolhimento.',
  },
  {
    number: 54,
    name: 'Nithael',
    hebrew: 'ניתאל',
    hebrewRoot: 'נית',
    psalm: 'Salmo 102:19',
    psalmText: 'O Senhor estabeleceu o seu trono nos céus, e o seu reino domina sobre tudo.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Sucesso e boa reputação.',
  },
  {
    number: 55,
    name: 'Mebahiah',
    hebrew: 'מבהיה',
    hebrewRoot: 'מבה',
    psalm: 'Salmo 101:13',
    psalmText: 'Mas tu, Senhor, permanecerás para sempre, e a tua memória de geração em geração.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Moralidade e apoio na religião.',
  },
  {
    number: 56,
    name: 'Poiel',
    hebrew: 'פויאל',
    hebrewRoot: 'פוי',
    psalm: 'Salmo 144:14',
    psalmText: 'O Senhor sustém a todos os que caem, e levanta a todos os abatidos.',
    divineName: 'El',
    hierarchy: 'Principados',
    virtues: 'Fortuna, filosofia e generosidade.',
  },
  {
    number: 57,
    name: 'Nemamiah',
    hebrew: 'נממיה',
    hebrewRoot: 'נממ',
    psalm: 'Salmo 113:19',
    psalmText: 'Os que temem ao Senhor confiam no Senhor; ele é o seu auxílio e o seu escudo.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Prosperidade e coragem.',
  },
  {
    number: 58,
    name: 'Ieialel',
    hebrew: 'יילאל',
    hebrewRoot: 'ייל',
    psalm: 'Salmo 6:4',
    psalmText: 'A minha alma está também muito perturbada; mas tu, Senhor, até quando?',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Cura de problemas oculares e tristeza.',
  },
  {
    number: 59,
    name: 'Harael',
    hebrew: 'הרחאל',
    hebrewRoot: 'הרח',
    psalm: 'Salmo 112:3',
    psalmText: 'Desde o nascimento do sol até ao ocaso, seja louvado o nome do Senhor.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Gestão de bens e fertilidade intelectual.',
  },
  {
    number: 60,
    name: 'Mitzrael',
    hebrew: 'מצראל',
    hebrewRoot: 'מצר',
    psalm: 'Salmo 144:17',
    psalmText: 'Justo é o Senhor em todos os seus caminhos, e santo em todas as suas obras.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Cura de doenças mentais e libertação.',
  },
  {
    number: 61,
    name: 'Umabel',
    hebrew: 'ומבאל',
    hebrewRoot: 'ומב',
    psalm: 'Salmo 112:2',
    psalmText: 'Seja bendito o nome do Senhor, desde agora e para sempre.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Amizade e interesse pela física e astrologia.',
  },
  {
    number: 62,
    name: 'Iah-Hel',
    hebrew: 'יההאל',
    hebrewRoot: 'יהה',
    psalm: 'Salmo 118:159',
    psalmText: 'Considera como amo os teus preceitos; vivifica-me, Senhor, segundo a tua benignidade.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Iluminação e sabedoria.',
  },
  {
    number: 63,
    name: 'Anauel',
    hebrew: 'ענואל',
    hebrewRoot: 'ענו',
    psalm: 'Salmo 2:11',
    psalmText: 'Servi ao Senhor com temor, e alegrai-vos com tremor.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Saúde e sucesso no comércio.',
  },
  {
    number: 64,
    name: 'Mehiel',
    hebrew: 'מחיאל',
    hebrewRoot: 'מחי',
    psalm: 'Salmo 32:18',
    psalmText: 'Eis que os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia.',
    divineName: 'Yah',
    hierarchy: 'Arcanjos',
    virtues: 'Sucesso acadêmico e literário.',
  },
  {
    number: 65,
    name: 'Damabiah',
    hebrew: 'דמביה',
    hebrewRoot: 'דמב',
    psalm: 'Salmo 89:13',
    psalmText: 'Volta-te, Senhor, até quando? E aplaca-te para com os teus servos.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Sucesso em negócios marítimos e sabedoria.',
  },
  {
    number: 66,
    name: 'Manakel',
    hebrew: 'מנקאל',
    hebrewRoot: 'מנק',
    psalm: 'Salmo 37:22',
    psalmText: 'Não me desampares, Senhor; meu Deus, não te alongues de mim.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Apaziguamento da ira e sonhos proféticos.',
  },
  {
    number: 67,
    name: 'Eiael',
    hebrew: 'איעאל',
    hebrewRoot: 'איע',
    psalm: 'Salmo 36:4',
    psalmText: 'Deleita-te também no Senhor, e te concederá os desejos do teu coração.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Consolação nas adversidades e sabedoria oculta.',
  },
  {
    number: 68,
    name: 'Habuhiah',
    hebrew: 'חבויה',
    hebrewRoot: 'חבו',
    psalm: 'Salmo 105:1',
    psalmText: 'Louvai ao Senhor, porque ele é bom; porque a sua misericórdia dura para sempre.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Cura e fecundidade agrícola.',
  },
  {
    number: 69,
    name: 'Rochel',
    hebrew: 'ראהאל',
    hebrewRoot: 'ראה',
    psalm: 'Salmo 15:5',
    psalmText: 'O Senhor é a porção da minha herança e do meu cálice; tu sustentas a minha sorte.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Recuperação de objetos perdidos e renome.',
  },
  {
    number: 70,
    name: 'Jabamiah',
    hebrew: 'יבמיה',
    hebrewRoot: 'יבמ',
    psalm: 'Salmo 1:1',
    psalmText: 'No princípio criou Deus os céus e a terra.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Regeneração e transformação espiritual.',
  },
  {
    number: 71,
    name: 'Haiaiel',
    hebrew: 'הייאל',
    hebrewRoot: 'היי',
    psalm: 'Salmo 108:30',
    psalmText: 'Louvarei grandemente ao Senhor com a minha boca; louvá-lo-ei entre a multidão.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Vitória e proteção contra injustiças.',
  },
  {
    number: 72,
    name: 'Mumiah',
    hebrew: 'מומיה',
    hebrewRoot: 'מומ',
    psalm: 'Salmo 114:7',
    psalmText: 'Volta, minha alma, a teu repouso, porque o Senhor te fez bem.',
    divineName: 'El',
    hierarchy: 'Anjos',
    virtues: 'Finalização de tarefas e segredos da saúde.',
  },
] as const;

function buildAngel(data: (typeof ANGEL_DATA)[number], index: number): Angel72 {
  const degreesStart = index * 5;
  const degreesEnd = index === 71 ? 360 : degreesStart + 5;
  const sign = getZodiacSignFromLongitude(degreesStart);

  return {
    ...data,
    sign,
    degreesStart,
    degreesEnd,
  };
}

export const ANGELS_72: readonly Angel72[] = ANGEL_DATA.map((entry, index) => buildAngel(entry, index));

export function getAngelIndex(longitude: number): number {
  const normalized = normalizeLongitude(longitude);
  return Math.floor(normalized / 5) % ANGELS_72.length;
}

export function getAngelByDegree(longitude: number): Angel72 {
  return ANGELS_72[getAngelIndex(longitude)];
}
